# Generated by Django 5.0.5 on 2024-07-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_fooditem_addtobag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='img',
            field=models.ImageField(upload_to='food_img/'),
        ),
    ]
