# Generated by Django 5.0.5 on 2024-07-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_placeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
